from __future__ import annotations

# A small seed set of recently verified local reporting. The live news client
# supplements this list and the editorial layer automatically ignores stale items.
CURATED_NEWS = [
    {
        "title": "Historic building in San Francisco's Presidio to become coworking hub",
        "url": "https://www.sfchronicle.com/sf/article/canopy-presidio-coworking-22390609.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-17T08:00:00-07:00",
        "beat": "businesses",
        "neighborhoods": ["Presidio"],
        "summary": "A restored 40,000-square-foot Main Post building is becoming a Canopy coworking hub, adding a major commercial use to the Presidio.",
    },
    {
        "title": "It's the first day of school in S.F. Some students are stepping into a brand new campus",
        "url": "https://www.sfchronicle.com/sf/article/s-f-students-return-school-mission-bay-school-22385475.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-17T07:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Mission Bay"],
        "summary": "Mission Bay's new $130 million public school opened as the fast-growing neighborhood adds civic infrastructure alongside housing and employment growth.",
    },
    {
        "title": "S.F.'s Marina Safeway project clears key hurdle, moves closer to approval",
        "url": "https://www.sfchronicle.com/sf/article/marina-safeway-tower-approved-22387853.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-15T10:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Marina"],
        "summary": "City planners confirmed the 848-unit Marina Safeway redevelopment can use state housing streamlining, moving the unusually large neighborhood project closer to approval.",
    },
    {
        "title": "This Mission laundromat became a symbol of S.F.'s housing wars. It's finally being redeveloped",
        "url": "https://www.sfchronicle.com/sf/article/housing-mission-laundromat-22387110.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-14T10:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Mission"],
        "summary": "A long-disputed Mission Street laundromat site is moving ahead as a 75-unit apartment project after years of debate over development and displacement.",
    },
    {
        "title": "Inside the $62 million renovation replacing SoMa's cramped old gym",
        "url": "https://www.sfchronicle.com/sf/article/soma-gene-friend-rec-center-reopens-22378382.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-13T09:00:00-07:00",
        "beat": "service_requests",
        "neighborhoods": ["South of Market"],
        "summary": "The rebuilt Gene Friend Recreation Center opened at Sixth and Folsom, a major public-space investment in a growing part of SoMa.",
    },
    {
        "title": "'Can I survive?': S.F. Chinatown merchants struggle amid park renovation",
        "url": "https://www.sfchronicle.com/sf/article/chinatown-portsmouth-square-construction-22377597.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-11T09:00:00-07:00",
        "beat": "businesses",
        "neighborhoods": ["Chinatown"],
        "summary": "Portsmouth Square's two-year reconstruction is cutting foot traffic and disrupting merchants, giving important context to business and street-service signals in Chinatown.",
    },
    {
        "title": "S.F. police arrest 2 men in SoMa neighborhood killing",
        "url": "https://www.sfchronicle.com/bayarea/article/san-francisco-homicide-arrests-san-rafael-22382629.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-11T08:00:00-07:00",
        "beat": "police",
        "neighborhoods": ["South of Market"],
        "summary": "Two arrests were announced in connection with a March fatal shooting near Third and Harrison, a reminder that individual cases can affect short weekly public-safety signals.",
    },
    {
        "title": "S.F.'s controversial housing rezoning is now in effect. Where are all the projects?",
        "url": "https://www.sfchronicle.com/sf/article/housing-family-zoning-22378281.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-10T09:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Inner Richmond", "Outer Richmond", "Inner Sunset", "Sunset/Parkside"],
        "summary": "The new family-zoning rules have produced relatively few projects so far, suggesting financing and construction economics still constrain permit activity even where zoning capacity increased.",
    },
    {
        "title": "A restaurant renaissance is coming to this historic S.F. neighborhood",
        "url": "https://www.sfchronicle.com/food/restaurants/article/bayview-oyster-bar-sf-opening-22362147.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-08-10T08:00:00-07:00",
        "beat": "businesses",
        "neighborhoods": ["Bayview Hunters Point"],
        "summary": "A city-backed storefront program is helping seed a cluster of new restaurants and cultural businesses along Third Street in the Bayview.",
    },
    {
        "title": "Tartine is bringing its famed bread to downtown San Francisco",
        "url": "https://www.sfchronicle.com/realestate/article/tartine-bakery-downtown-san-francisco-22366216.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-07-30T09:00:00-07:00",
        "beat": "businesses",
        "neighborhoods": ["Financial District/South Beach"],
        "summary": "Tartine is taking a 4,000-square-foot Financial District storefront, a notable tenant win for a downtown area still working through commercial vacancies.",
    },
    {
        "title": "One of S.F.'s biggest developments is changing its plans",
        "url": "https://www.sfchronicle.com/realestate/article/one-s-f-s-biggest-developments-changing-plans-22365461.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-07-29T09:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Potrero Hill"],
        "summary": "The Potrero Power Station development is seeking entitlement changes as post-pandemic financing, construction costs and office demand reshape the economics of large projects.",
    },
    {
        "title": "Map shows San Francisco crime rates broken down by neighborhood",
        "url": "https://www.sfchronicle.com/projects/2026/san-francisco-crime-neighborhood/",
        "publisher": "San Francisco Chronicle",
        "published": "2026-07-14T15:27:00-07:00",
        "beat": "police",
        "neighborhoods": [],
        "summary": "A citywide neighborhood analysis using the same DataSF incident-report dataset shows why raw counts and small weekly percentage changes need neighborhood and population context.",
    },
    {
        "title": "Crime in San Francisco is down — except homicides. Here's what's going on",
        "url": "https://www.sfchronicle.com/crime/article/san-francisco-homicide-data-22322670.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-07-14T09:00:00-07:00",
        "beat": "police",
        "neighborhoods": [],
        "summary": "Reported violent and property crime continued declining citywide in the first half of 2026 even as homicides remained elevated, reinforcing the need to separate individual categories from the overall trend.",
    },
    {
        "title": "San Francisco's office-to-housing push is finally showing signs of life",
        "url": "https://www.sfchronicle.com/sf/article/housing-office-conversions-22340479.php",
        "publisher": "San Francisco Chronicle",
        "published": "2026-07-13T09:00:00-07:00",
        "beat": "permits",
        "neighborhoods": ["Financial District/South Beach", "South of Market", "Hayes Valley"],
        "summary": "Several office-to-residential conversion applications are emerging after years of policy work, providing a citywide reason to watch permit activity in downtown and adjacent neighborhoods.",
    },
]
